### ISSUE TITLE
GPU Support TODO List

### ISSUE THREAD

**Issue by ExpandingMan** [dmlc/XGBoost.jl#134]
The following needs to be done for this wrapper to get GPU support.  From the C API docs it looks like this would mean only nvidia as I think it necessarily relies on CUDA.

- [ ] Create a new `xgboost_jll`.  I really have no idea how to do this for GPU targets, so that'll take some figuring out.  If anybody is good with BinaryBuilder and wants to help with that it would be much appreciated, as this is the step that would likely take me personally the vast majority of the effort.
- [ ] Check that the array handles in CUDA.jl are the same as those expected by the libxgboost API.  If they are not we'll have to figure out what the difference is.
- [ ] Add CUDA.jl as a dependency.  I think this is a complete non-issue as `using CUDA` works fine on machines without an nvidia GPU.

**Comment by Roh-codeur** [comment]
thanks for your work on this, I look forward to seeing this. will add a significant impact on my project, thanks!

**Comment by Roh-codeur** [comment]
@ExpandingMan : hey mate, thanks for your help with this. did you get a chance to make progress with this? this will be of tremendous help to my project

thanks
Roh

**Comment by ExpandingMan** [comment]
I have not, but I also have not forgotten about it.

The part of this with the most question marks in my mind is how exactly to setup the `xgboost_jll` which I'm going to have to figure out to some extent before I even attempt to make a wrapper.  So if anyone wants to help this along getting the `xgboost_jll` updated to include GPU support and automatically use that build when nvidia cards are present would be best way to do that.

**Comment by Roh-codeur** [comment]
ahh ok, sorry, not my area of expertise or even knowhow. thanks for your help in this, ta!

**Comment by tylerjthomas9** [comment]
Full GPU support is now available in `v2.2.0` (https://github.com/dmlc/XGBoost.jl/pull/142).

**Comment by Roh-codeur** [comment]
> Full GPU support is now available in `v2.2.0` (#142).

this is awesome! thanks a lot @tylerjthomas9 and everyone else who helped.

**Comment by tylerjthomas9** [comment]
> this is awesome! thanks a lot @tylerjthomas9 and everyone else who helped.

@ExpandingMan is the primary person behind all the recent improvements to XGBoost.jl

**Comment by ExpandingMan** [comment]
Forgive the mutual admiration society, but by *far* the hardest part of doing this was updating the `XGBoost_jll` to properly handle CUDA dependencies which was done by @tylerjthomas9 .  The wrapper part was, fortunately quite easy, thanks in part to the very easy to use CUDA.jl.

So yes, I think this wrapper with GPU support is a nice success story for the Julia wrapping and packaging ecosystem :smile:
